### ISSUE TITLE
Missing Exports in PDFJS

### ISSUE THREAD

**Issue by nicolas-schreiber** [acchou/pdf.js#1]
I wanted to comment on https://github.com/mozilla/pdf.js/pull/9369#issuecomment-363850989.

This:
```
// Assuming pdf_viewer.js is loaded via script tag
import { showPreviousViewOnLoad } from "pdfjs-dist";
if(showPreviousViewOnLoad) { ... } // ok
showPreviousViewOnLoad = true; // type error: cannot assign to 'showPreviousViewOnLoad' because it is not a variable
```
is not the way I am using the code.

The variables are in the namespace PDFJS. Therefore I set them like this:
```
import { PDFJS } from "pdfjs-dist";
PDFJS.showPreviousViewOnLoad = false;
```
I do not get a type error or anything.
And it is very useful for setting things like: disableTextLayer or useOnlyCssZoom.

Oh yeah, and you are right, they can only be accessed when adding the viewer separately.

**Comment by acchou** [comment]
Thanks, that clarifies things. Would you mind creating a PR against my `typescript` branch that includes your change from https://github.com/nicolas-schreiber/pdf.js/commit/08321877b298d78afc6ddf33e7e3044f10134a22 along with the following changes:

- [ ] Add a comment in `display.d.ts` showing where in the pdf.js code base the variables are defined or specified.  Currently the file is organized by having comments like this: https://github.com/nicolas-schreiber/pdf.js/blob/08321877b298d78afc6ddf33e7e3044f10134a22/external/types/display.d.ts#L17 which specify the file where the subsequent declarations are from in the pdf.js code base. For example, the code you added is after the declaration for `disableWebGL` in `src/display/global.js`, but that's not where these variables can be found. Add a new comment if there's a new file in the pdf.js code base that's being referenced.
- [ ] Move the declarations in `pdf.d.ts` under the section for `web/pdf_viewer.component.js`. Could you also add a comment describing that all of the stuff there is only accessible if you use the viewer component.

If you'd rather that I make these changes just describe what the comments above should be.

**Comment by nicolas-schreiber** [comment]
Just created the PR. I took the weekend off so it took a bit.

**Comment by acchou** [comment]
I just reverted this per the discussion on https://github.com/mozilla/pdf.js/pull/9369. I'd suggest creating a new PR if you feel there are still variables you'd like to add, but this time we'll have someone from the PDFJS team review first. Thanks for trying to help though, appreciate that and I'm sure there will be changes to come to the API where your help would be welcome.
